"""match outcome columns

Revision ID: 088791e75352
Revises: b44af5ce86f4
Create Date: 2026-06-28 12:22:11.821754
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "088791e75352"
down_revision: str | None = "b44af5ce86f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match", sa.Column("team_a_id", sa.BigInteger(), nullable=True))
    op.add_column("match", sa.Column("team_b_id", sa.BigInteger(), nullable=True))
    op.add_column("match", sa.Column("winner_team_id", sa.BigInteger(), nullable=True))
    op.add_column("match", sa.Column("score_a", sa.Integer(), nullable=True))
    op.add_column("match", sa.Column("score_b", sa.Integer(), nullable=True))
    op.create_index("ix_match_team_a_id", "match", ["team_a_id"], unique=False)
    op.create_index("ix_match_team_b_id", "match", ["team_b_id"], unique=False)
    op.create_index("ix_match_winner_team_id", "match", ["winner_team_id"], unique=False)
    op.create_foreign_key(None, "match", "team", ["winner_team_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "match", "team", ["team_a_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "match", "team", ["team_b_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_constraint(None, "match", type_="foreignkey")
    op.drop_index("ix_match_winner_team_id", table_name="match")
    op.drop_index("ix_match_team_b_id", table_name="match")
    op.drop_index("ix_match_team_a_id", table_name="match")
    op.drop_column("match", "score_b")
    op.drop_column("match", "score_a")
    op.drop_column("match", "winner_team_id")
    op.drop_column("match", "team_b_id")
    op.drop_column("match", "team_a_id")
    # ### end Alembic commands ###
