"""initial schema

Revision ID: b44af5ce86f4
Revises:
Create Date: 2026-06-27 23:54:24.393524
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b44af5ce86f4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "map",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("in_pool", sa.Boolean(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_map_name"),
    )
    op.create_table(
        "match",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("vlr_match_id", sa.Text(), nullable=False),
        sa.Column("event", sa.Text(), nullable=False),
        sa.Column("played_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vlr_match_id", name="uq_match_vlr_id"),
    )
    op.create_index("ix_match_event", "match", ["event"], unique=False)
    op.create_index("ix_match_played_at", "match", ["played_at"], unique=False)
    op.create_table(
        "player",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("handle", sa.Text(), nullable=False),
        sa.Column("vlr_player_id", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vlr_player_id", name="uq_player_vlr_id"),
    )
    op.create_table(
        "ranking",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tournament_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("data_window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("config_hash", sa.Text(), nullable=False),
        sa.Column("supersedes_ranking_id", sa.BigInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["supersedes_ranking_id"], ["ranking.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="uq_ranking_version"),
    )
    op.create_table(
        "team",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("vlr_team_id", sa.Text(), nullable=True),
        sa.Column("is_enc_2026", sa.Boolean(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "country", name="uq_team_name_country"),
        sa.UniqueConstraint("vlr_team_id", name="uq_team_vlr_id"),
    )
    op.create_index("ix_team_is_enc_2026", "team", ["is_enc_2026"], unique=False)
    op.create_table(
        "match_map",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_id", sa.BigInteger(), nullable=False),
        sa.Column("map_id", sa.BigInteger(), nullable=False),
        sa.Column("winner_team_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(["map_id"], ["map.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["match_id"], ["match.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["winner_team_id"], ["team.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "map_id", name="uq_match_map"),
    )
    op.create_index("ix_match_map_map_id", "match_map", ["map_id"], unique=False)
    op.create_index("ix_match_map_match_id", "match_map", ["match_id"], unique=False)
    op.create_table(
        "outcome_comparison",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ranking_id", sa.BigInteger(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metric", sa.Text(), nullable=False),
        sa.Column("predicted_value", sa.Numeric(), nullable=False),
        sa.Column("baseline_label", sa.Text(), nullable=False),
        sa.Column("baseline_value", sa.Numeric(), nullable=False),
        sa.Column("final_standings_source", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["ranking_id"], ["ranking.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ranking_id", "metric", "baseline_label", name="uq_outcome_comparison"),
    )
    op.create_table(
        "ranking_entry",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ranking_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("team_score", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.CheckConstraint("position BETWEEN 1 AND 16", name="ck_ranking_entry_position"),
        sa.ForeignKeyConstraint(["ranking_id"], ["ranking.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ranking_id", "position", name="uq_ranking_entry_position"),
        sa.UniqueConstraint("ranking_id", "team_id", name="uq_ranking_entry_team"),
    )
    op.create_table(
        "ranking_map_breakdown",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ranking_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("map_id", sa.BigInteger(), nullable=False),
        sa.Column("map_score", sa.Numeric(precision=8, scale=4), nullable=False),
        sa.Column("confidence", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["map_id"], ["map.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["ranking_id"], ["ranking.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ranking_id", "team_id", "map_id", name="uq_ranking_map_breakdown"),
    )
    op.create_table(
        "team_player",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("team_id", "player_id", name="uq_team_player"),
    )
    op.create_index("ix_team_player_player_id", "team_player", ["player_id"], unique=False)
    op.create_table(
        "player_map_stat",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("match_map_id", sa.BigInteger(), nullable=False),
        sa.Column("player_id", sa.BigInteger(), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=True),
        sa.Column("rating", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("acs", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("kast", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("adr", sa.Numeric(precision=6, scale=1), nullable=True),
        sa.Column("kills", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column("assists", sa.Integer(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["match_map_id"], ["match_map.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["player.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["team.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_map_id", "player_id", name="uq_player_map_stat"),
    )
    op.create_index(
        "ix_player_map_stat_match_map_id", "player_map_stat", ["match_map_id"], unique=False
    )
    op.create_index("ix_player_map_stat_player_id", "player_map_stat", ["player_id"], unique=False)
    op.create_index("ix_player_map_stat_team_id", "player_map_stat", ["team_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_player_map_stat_team_id", table_name="player_map_stat")
    op.drop_index("ix_player_map_stat_player_id", table_name="player_map_stat")
    op.drop_index("ix_player_map_stat_match_map_id", table_name="player_map_stat")
    op.drop_table("player_map_stat")
    op.drop_index("ix_team_player_player_id", table_name="team_player")
    op.drop_table("team_player")
    op.drop_table("ranking_map_breakdown")
    op.drop_table("ranking_entry")
    op.drop_table("outcome_comparison")
    op.drop_index("ix_match_map_match_id", table_name="match_map")
    op.drop_index("ix_match_map_map_id", table_name="match_map")
    op.drop_table("match_map")
    op.drop_index("ix_team_is_enc_2026", table_name="team")
    op.drop_table("team")
    op.drop_table("ranking")
    op.drop_table("player")
    op.drop_index("ix_match_played_at", table_name="match")
    op.drop_index("ix_match_event", table_name="match")
    op.drop_table("match")
    op.drop_table("map")
    # ### end Alembic commands ###
