"""team country nullable for clubs

Revision ID: bd877689ee75
Revises: 088791e75352
Create Date: 2026-06-28 12:31:02.684556
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd877689ee75"
down_revision: str | None = "088791e75352"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("team", "country", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("team", "country", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
